
        
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build application
        run: echo "Build commands for your application"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version:'3.x'

      - name : Install pytest and coverage 
        run : |
          pip install pytest pytest-cov

      - name : Run tests with coverage report 
        run : |
          pytest --cov=./ 

  scan:
    needs:test 
    runs-on : ubuntu-latest 
    steps :
     - name : Checkout code 
       uses : actions/checkout@v2 

     - name : SonarQube Scan 
       uses : sonarsource/sonarcloud-github-action@master 
       env :
         GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}  
         SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}

  deploy_needs_approval:
    needs:[scan]
    runs-on:[ubuntu-latest]
    environment:name:"production"
    
  deploy_to_aws_ecs :
   needs:[deploy_needs_approval]
   runs-on:[ubuntu-latest]
   steps :
     - name:Setup AWS CLI 
       uses:"aws-actions/configure-aws-credentials@v1"
       with :
         aws-access-key-id:${{secrets.AWS_ACCESS_KEY_ID}}
         aws-secret-access-key:${{secrets.AWS_SECRET_ACCESS_KEY}}
         aws-region:${{secrets.AWS_REGION}}

     -name:ECS Deploy Commands  
       run :"Your ECS deployment commands go here"

        