
        
name: Multi-Stage Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build application
        run: |
          # Add commands to build the application here

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python and coverage tooling 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
      - name : Run tests and generate coverage report 
        run : | 
          pytest --cov-report=xml --cov=.
      
  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name : SonarQube Scan 
        uses : sonarsource/sonarcloud-github-action@master 
        env :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}

  deploy:
    name : Deploy 
    runs-on : ubuntu-latest 
    needs : scan  
    steps :
      - name : Deploy to AWS ECS  
        run : |  
          # Add commands to deploy to AWS ECS using AWS CLI and ECS commands here

  approval_gate:
   if : always()
   needs :
     - deploy  
   runs-on :
     ubuntu-latest  
   steps :
     - name : Manual Approval  
       uses : appleboy/approval-action@v1.0.0  
       with :
         github_token : ${{ secrets.GITHUB_TOKEN }}

        