
        
name: Node.js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

  scan:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codeql-analysis:
    needs: scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  
  deploy_review:
     needs : codeql-analysis 
     runs-on : ubuntu-latest 
     
     steps :
       - name : Wait for approval 
         uses : pascalgn/automerge-action@v0.13.0 
         with :
           merge_method : squash 
           pull_request_review_state : approved 

  deploy_to_azure :
     needs : deploy_review 
     runs-on : ubuntu-latest 

     steps :
       - name : Login via Az module 
         run : |
           az login --service-principal --username ${{ secrets.AZURE_APP_ID }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

       - name : Deploy to Azure Web App 
         run : |
           az webapp deployment source config-zip --resource-group myResourceGroup --name myApp --src <path-to-zip-file>

        