
        
name: Multi-Stage Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run tests with coverage report
        run: |
          pytest --cov-report=xml --cov=.

  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master

  deploy:
    name: Deploy to AWS ECS (Manual Approval Required)
    runs-on: ubuntu-latest    
    needs:
      - scan      
    steps:
      - name : Deploy to AWS ECS      
        run : |
          # Add commands to deploy to AWS ECS using AWS CLI and ECS commands here.

        