
        
name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  codeql-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['javascript']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        
      - name: Autobuild CodeQL database
        uses: github/codeql-action/autobuild@v1
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  deploy-to-azure-app-service:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS }}
      
      - name : Set up Azure WebApp for Containers 
        uses : azure/webapps-deploy@v2 
        with :
          app-name : 'your-app-name'
          images : 'your-docker-image'

        