
        
name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
  sonarqube_scan:

    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    
     # Assuming you have setup SonarQube server and have the token stored as a secret in your repo.
     
     - name : Checkout Code 
       uses : actions/checkout@v2
     
     - name : SonarQube Scan 
       uses : sonarsource/sonarqube-scan-action@master 
       env :
         SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
         
  deploy_to_azure:

     needs: sonarqube_scan
     
     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
     
     runs-on : ubuntu-latest
     
     steps :
     
     - name : Checkout Code 
       uses : actions/checkout@v2
     
     - name : Login to Azure 
       uses : azure/login@v1 
       with :
         creds : ${{ secrets.AZURE_CREDENTIALS }}
         
     # Assuming you have setup Azure App Service and have the app-name and slot-name.
     
     - name : Deploy to Azure App Service 
       uses : azure/webapps-deploy@v2 
       with :
         app-name : '<app-name>'
         slot-name : '<slot-name>'
         package-path : '.'

        